version: '3.8'

services:
  # Laravel PHP-FPM container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    networks:
      - laravel
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=crowdfunding
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  # MySQL Database container
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: crowdfunding
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  # Nginx container
  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:


volumes:
  mysql_data:
    driver: local
